lsb_vsx: added little changes after review

diff --git a/lsb_vsx/lsb_vsx-2.0-1-config/patches/01_install.patch b/lsb_vsx/lsb_vsx-2.0-1-config/patches/01_install.patch
--- a/lsb_vsx/lsb_vsx-2.0-1-config/patches/01_install.patch
+++ b/lsb_vsx/lsb_vsx-2.0-1-config/patches/01_install.patch
@@ -1,222 +1,263 @@
-46,142d45
-< ######################################################################
-< # Add a group. Try to be tolerant of different groupadd arguments
-< add_single_group()
-< {
-<   if [ -n "$GROUP_ID" ]; then
-<     GROUP_ID=$(($GROUP_ID+1))
-<     GROUP_FLAGS="-g $GROUP_ID"
-<   fi
-<   set -x
-<   groupadd $GROUP_FLAGS $1
-<   GROUP_ADD=$?
-<   set +x
-<   if [ $GROUP_ADD -ne 0 -a -z "$GROUP_ID" ]; then
-<     grep $1 /etc/group
-<     if [ $? -ne 0 ]; then
-<       # work out a group id we can use
-<       # Serious dodgy algorithm but avoids the problem of 
-<       # nogroup often being set to the last valid gid
-<       echo
-<       echo Possibly detected different group add implementation
-<       echo Trying to workaround by supplying -G flag
-<       echo
-<       GROUP_ID=`cut -f3 -d: /etc/group | sort -n | tail -2 | head -1`;
-<       GROUP_ID=$(($GROUP_ID+10))
-<       GROUP_FLAGS="-g $GROUP_ID"
-<       set -x
-<       groupadd $GROUP_FLAGS $1
-<       set +x
-<     fi
-<   fi
-< }
-< 
-< uidsetup() 
-< {
-<   # add the maximum number of groups for a user
-<   echo "Adding the groups"
-<   add_single_group  vsxg0
-<   add_single_group  vsxg1
-<   add_single_group  vsxg2
-<   # note that this is to NGROUP_MAX , vsxg0 + NGROUP_MAX supp groups
-<   add_single_group  supp1
-<   add_single_group  supp2
-<   add_single_group  supp3
-<   add_single_group  supp4
-<   add_single_group  supp5
-<   add_single_group  supp6
-<   add_single_group  supp7
-<   add_single_group  supp8
-<   add_single_group  supp9
-<   add_single_group  supp10
-<   add_single_group  supp11
-<   add_single_group  supp12
-<   add_single_group  supp13
-<   add_single_group  supp14
-<   add_single_group  supp15
-<   add_single_group  supp16
-<   add_single_group  supp17
-<   add_single_group  supp18
-<   add_single_group  supp19
-<   add_single_group  supp20
-<   add_single_group  supp21
-<   add_single_group  supp22
-<   add_single_group  supp23
-<   add_single_group  supp24
-<   add_single_group  supp25
-<   add_single_group  supp26
-<   add_single_group  supp27
-<   add_single_group  supp28
-<   add_single_group  supp29
-<   add_single_group  supp30
-<   add_single_group  supp31
-<   
-<   echo "Adding the users"
-<   
-<   set -x
-<   
-<   # you may prefer the ksh to sh
-<   useradd -g vsxg0 -d $TET_ROOT/test_sets -s /bin/sh -c "VSX0 test login" vsx0
-<   # We add the supplementary groups separately just in case the vsx0
-<   # user already exists but without the required groups
-< 
-<   # If we have a GROUP_ID set then we're probably on a system that has a
-<   # modified usermod command as well.
-<   if [ -z "$GROUP_ID" ]; then
-<     USER_MOD_FLAG="-G"
-<   else
-<     USER_MOD_FLAG="-g"
-<   fi
-< 
-<   usermod $USER_MOD_FLAG supp1,supp2,supp3,supp4,supp5,supp6,supp7,supp8,supp9,supp10,supp11,supp12,supp13,supp14,supp15,supp16,supp17,supp18,supp19,supp20,supp21,supp22,supp23,supp24,supp25,supp26,supp27,supp28,supp29,supp30,supp31 vsx0
-<   useradd -g vsxg1 -d $TET_ROOT -s /bin/sh -c "VSX1 test login" vsx1
-<   useradd -g vsxg2 -d $TET_ROOT -s /bin/sh -c "VSX2 test login" vsx2
-<   set +x
-<   echo "Enter the password for the vsx0 user"
-<   passwd vsx0
-< }
-< 
-154c57
-<   yacc --version > /dev/null 2>&1
----
->   yacc --version > /dev/null 2&>1
-165d67
-< 
-170,175d71
-< # Check we're running as root
-< if  [ $EUID -ne 0 ]; then
-<   echo "This installation script must be run as root"
-<   exit 1
-< fi
-< 
-190d85
-< echo
-194a90,91
-> TET_ROOT=${PREFIX_LSB_VSX_BUILD}/files
-> export TET_ROOT
-196,202c93,94
-< printf "Enter root directory of test suite installation: [/home/tet] "
-< read cmd
-< if [ "$cmd" = "" ]; then
-<   cmd=/home/tet
-< fi
-< if [ ! -d $cmd ]; then
-<   mkdir $cmd
----
-> if [ ! -d ${TET_ROOT} ]; then
->   mkdir ${TET_ROOT}
-204c96
-<     echo "Unable to create installation directory: $cmd"
----
->     echo "Unable to create installation directory: ${TET_ROOT}"
-208,209d99
-< TET_ROOT=$cmd
-< export TET_ROOT
-211,232d100
-< # Check that user id's are setup
-< # We check that vsx1 user exists instead of vsx0 as some
-< # test suites have more stringent user and group requirments
-< # than others
-< grep vsx1 /etc/passwd 2>&1 >/dev/null
-< if [ $? -ne 0 ]; then
-<   printf "The required users and groups are not setup correctly\n"
-<   printf "Do you wish to install the user and groups ..?[y]"
-<   read cmd
-<   if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
-<       uidsetup
-<   else
-<     echo "Please setup required users and groups manually and rerun"
-<     echo "the installation script"
-<   fi
-< else
-<   echo "Setting vsx0, vsx1 and vsx2 users' home directories"
-<   echo "You may need to re-login any existing shells for these users"
-<   usermod -d $TET_ROOT/test_sets vsx0
-<   usermod -d $TET_ROOT vsx1
-<   usermod -d $TET_ROOT vsx2
-< fi
-236,240c104,109
-< tet_package=`ls -1 tet_vsxgen_* 2> /dev/null | tail -1`
-< tet_package=${tet_package:-""}
-< if [ $tet_package ]; then
-<   tet_package="$PWD/$tet_package"
-< fi
----
-> # tet_package=`ls -1 tet_vsxgen_* 2> /dev/null | tail -1`
-> # tet_package=${tet_package:-""}
-> # if [ $tet_package ]; then
-> #   tet_package="$PWD/$tet_package"
-> # fi
-> tet_package=${PREFIX_LSB_VSX}/tet_vsxgen_3.02.tgz
-242,246d110
-< printf "TET and VSxgen package to install [$tet_package]: "
-< read cmd
-< if [ "$cmd" != "" ]; then
-<   tet_package=$cmd
-< fi
-253d116
-< 
-260a124
-> cd ${PREFIX_LSB_VSX}
-263,267d126
-< printf "Test suites to be installed [$test_suites]: "
-< read cmd
-< if [ "$cmd" != "" ]; then
-<   test_suites=$cmd
-< fi
-284,318d142
-< 
-< # Set ownership correctly
-< echo Setting up ownership and permissions correctly
-< chown -R vsx0.vsxg0 $TET_ROOT
-< chmod u+x $TET_ROOT/setup.sh
-< 
-< # Display licence information
-< echo ----------------------------------------------------------------------
-< echo Licencing Conditions for test harness
-< echo 
-< 
-< sh $TET_ROOT/Licence.brief
-< printf "Press Enter to continue. "
-< read cmd
-< 
-< echo
-< echo ----------------------------------------------------------------------
-< echo Licencing Conditions for test suites
-< echo 
-< 
-< for i in $TET_ROOT/test_sets/scripts/*; do
-<   if [ -x $i/display_licence_brief.sh ]; then
-<     $i/display_licence_brief.sh
-<     printf "Press Enter to continue. "
-<     read cmd
-<     echo -------------------------------------------------------------------
-<   fi
-< done;
-< 
-< printf "\n\nYou should now login as the vsx0 user and run $TET_ROOT/setup.sh\n"
-< echo "Note that additional test suites can be installed by unpacking the"
-< echo "test suite tarball in $TET_ROOT/test_sets as the vsx0 user and re-running"
-< echo "$TET_ROOT/setup.sh (this will be ../setup.sh from the home directory)."
-< 
-< 
+--- install.sh	2022-07-19 14:16:30.660480136 +0200
++++ install.sh-phoenix	2022-09-08 17:00:59.497821808 +0200
+@@ -43,102 +43,7 @@
+ ######################################################################
+ # Useful functions
+ 
+-######################################################################
+-# Add a group. Try to be tolerant of different groupadd arguments
+-add_single_group()
+-{
+-  if [ -n "$GROUP_ID" ]; then
+-    GROUP_ID=$(($GROUP_ID+1))
+-    GROUP_FLAGS="-g $GROUP_ID"
+-  fi
+-  set -x
+-  groupadd $GROUP_FLAGS $1
+-  GROUP_ADD=$?
+-  set +x
+-  if [ $GROUP_ADD -ne 0 -a -z "$GROUP_ID" ]; then
+-    grep $1 /etc/group
+-    if [ $? -ne 0 ]; then
+-      # work out a group id we can use
+-      # Serious dodgy algorithm but avoids the problem of 
+-      # nogroup often being set to the last valid gid
+-      echo
+-      echo Possibly detected different group add implementation
+-      echo Trying to workaround by supplying -G flag
+-      echo
+-      GROUP_ID=`cut -f3 -d: /etc/group | sort -n | tail -2 | head -1`;
+-      GROUP_ID=$(($GROUP_ID+10))
+-      GROUP_FLAGS="-g $GROUP_ID"
+-      set -x
+-      groupadd $GROUP_FLAGS $1
+-      set +x
+-    fi
+-  fi
+-}
+-
+-uidsetup() 
+-{
+-  # add the maximum number of groups for a user
+-  echo "Adding the groups"
+-  add_single_group  vsxg0
+-  add_single_group  vsxg1
+-  add_single_group  vsxg2
+-  # note that this is to NGROUP_MAX , vsxg0 + NGROUP_MAX supp groups
+-  add_single_group  supp1
+-  add_single_group  supp2
+-  add_single_group  supp3
+-  add_single_group  supp4
+-  add_single_group  supp5
+-  add_single_group  supp6
+-  add_single_group  supp7
+-  add_single_group  supp8
+-  add_single_group  supp9
+-  add_single_group  supp10
+-  add_single_group  supp11
+-  add_single_group  supp12
+-  add_single_group  supp13
+-  add_single_group  supp14
+-  add_single_group  supp15
+-  add_single_group  supp16
+-  add_single_group  supp17
+-  add_single_group  supp18
+-  add_single_group  supp19
+-  add_single_group  supp20
+-  add_single_group  supp21
+-  add_single_group  supp22
+-  add_single_group  supp23
+-  add_single_group  supp24
+-  add_single_group  supp25
+-  add_single_group  supp26
+-  add_single_group  supp27
+-  add_single_group  supp28
+-  add_single_group  supp29
+-  add_single_group  supp30
+-  add_single_group  supp31
+-  
+-  echo "Adding the users"
+-  
+-  set -x
+-  
+-  # you may prefer the ksh to sh
+-  useradd -g vsxg0 -d $TET_ROOT/test_sets -s /bin/sh -c "VSX0 test login" vsx0
+-  # We add the supplementary groups separately just in case the vsx0
+-  # user already exists but without the required groups
+-
+-  # If we have a GROUP_ID set then we're probably on a system that has a
+-  # modified usermod command as well.
+-  if [ -z "$GROUP_ID" ]; then
+-    USER_MOD_FLAG="-G"
+-  else
+-    USER_MOD_FLAG="-g"
+-  fi
+-
+-  usermod $USER_MOD_FLAG supp1,supp2,supp3,supp4,supp5,supp6,supp7,supp8,supp9,supp10,supp11,supp12,supp13,supp14,supp15,supp16,supp17,supp18,supp19,supp20,supp21,supp22,supp23,supp24,supp25,supp26,supp27,supp28,supp29,supp30,supp31 vsx0
+-  useradd -g vsxg1 -d $TET_ROOT -s /bin/sh -c "VSX1 test login" vsx1
+-  useradd -g vsxg2 -d $TET_ROOT -s /bin/sh -c "VSX2 test login" vsx2
+-  set +x
+-  echo "Enter the password for the vsx0 user"
+-  passwd vsx0
+-}
++# Delete creation of user and group
+ 
+ # Sanity configuration check
+ SanityChecks()
+@@ -162,17 +67,10 @@
+     echo "system administrator."
+     exit 1
+   fi
+-
+ }
+ 
+ ######################################################################
+ 
+-# Check we're running as root
+-if  [ $EUID -ne 0 ]; then
+-  echo "This installation script must be run as root"
+-  exit 1
+-fi
+-
+ PATH=$PATH:/usr/sbin
+ export PATH
+ 
+@@ -187,70 +85,39 @@
+ echo "If you are installing a new version of the test harness or the last"
+ echo "installation failed for any reason it is recommended that you first"
+ echo "remove any the old installation."
+-echo
+ 
+ # Do sanity checks on installation to save problems later
+ SanityChecks
+ 
++#Install all files to TET_ROOT, which will be _build folder
++
++TET_ROOT=${PREFIX_LSB_VSX_BUILD}/files
++export TET_ROOT
+ # Find out where to install the test suite
+-printf "Enter root directory of test suite installation: [/home/tet] "
+-read cmd
+-if [ "$cmd" = "" ]; then
+-  cmd=/home/tet
+-fi
+-if [ ! -d $cmd ]; then
+-  mkdir $cmd
++if [ ! -d ${TET_ROOT} ]; then
++  mkdir ${TET_ROOT}
+   if [ $? -ne 0 ]; then
+-    echo "Unable to create installation directory: $cmd"
++    echo "Unable to create installation directory: ${TET_ROOT}"
+     exit 1
+   fi
+ fi
+-TET_ROOT=$cmd
+-export TET_ROOT
+ 
+-# Check that user id's are setup
+-# We check that vsx1 user exists instead of vsx0 as some
+-# test suites have more stringent user and group requirments
+-# than others
+-grep vsx1 /etc/passwd 2>&1 >/dev/null
+-if [ $? -ne 0 ]; then
+-  printf "The required users and groups are not setup correctly\n"
+-  printf "Do you wish to install the user and groups ..?[y]"
+-  read cmd
+-  if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
+-      uidsetup
+-  else
+-    echo "Please setup required users and groups manually and rerun"
+-    echo "the installation script"
+-  fi
+-else
+-  echo "Setting vsx0, vsx1 and vsx2 users' home directories"
+-  echo "You may need to re-login any existing shells for these users"
+-  usermod -d $TET_ROOT/test_sets vsx0
+-  usermod -d $TET_ROOT vsx1
+-  usermod -d $TET_ROOT vsx2
+-fi
+ 
+ # Install the tet and vsxgen package
+ # Default to latest version of tarball available
+-tet_package=`ls -1 tet_vsxgen_* 2> /dev/null | tail -1`
+-tet_package=${tet_package:-""}
+-if [ $tet_package ]; then
+-  tet_package="$PWD/$tet_package"
+-fi
++# tet_package=`ls -1 tet_vsxgen_* 2> /dev/null | tail -1`
++# tet_package=${tet_package:-""}
++# if [ $tet_package ]; then
++#   tet_package="$PWD/$tet_package"
++# fi
++tet_package=${PREFIX_LSB_VSX}/tet_vsxgen_3.02.tgz
+ echo "Installing the TET and VSXgen test harness"
+-printf "TET and VSxgen package to install [$tet_package]: "
+-read cmd
+-if [ "$cmd" != "" ]; then
+-  tet_package=$cmd
+-fi
+ if [ ! -f "$tet_package" ]; then
+   echo "Could not find file \"$tet_package\""
+   echo Aborting
+   exit 1
+ fi
+ 
+-
+ (cd $TET_ROOT && tar xfz $tet_package)
+ if [ $? -ne 0 ]; then
+   echo "Unable to unpack TET/VSXgen"
+@@ -258,13 +125,9 @@
+ fi
+ 
+ # Install the test suites
++cd ${PREFIX_LSB_VSX}
+ test_suites=`echo lts_*.tgz | sed -e s/\ +//`
+ echo installing test_suites: $test_suites
+-printf "Test suites to be installed [$test_suites]: "
+-read cmd
+-if [ "$cmd" != "" ]; then
+-  test_suites=$cmd
+-fi
+ 
+ current_dir=$PWD;
+ for test_suite in $test_suites; do
+@@ -281,38 +144,3 @@
+ sed -e "s@^echo Unconfigured@TET_ROOT=$TET_ROOT@" $TET_ROOT/profile.skeleton \
+   > $TET_ROOT/profile && rm $TET_ROOT/profile.skeleton
+ sed -e "s@^echo Unconfigured@TET_ROOT=$TET_ROOT@" $TET_ROOT/test_sets/profile.skeleton  > $TET_ROOT/test_sets/profile && rm $TET_ROOT/test_sets/profile.skeleton
+-
+-# Set ownership correctly
+-echo Setting up ownership and permissions correctly
+-chown -R vsx0.vsxg0 $TET_ROOT
+-chmod u+x $TET_ROOT/setup.sh
+-
+-# Display licence information
+-echo ----------------------------------------------------------------------
+-echo Licencing Conditions for test harness
+-echo 
+-
+-sh $TET_ROOT/Licence.brief
+-printf "Press Enter to continue. "
+-read cmd
+-
+-echo
+-echo ----------------------------------------------------------------------
+-echo Licencing Conditions for test suites
+-echo 
+-
+-for i in $TET_ROOT/test_sets/scripts/*; do
+-  if [ -x $i/display_licence_brief.sh ]; then
+-    $i/display_licence_brief.sh
+-    printf "Press Enter to continue. "
+-    read cmd
+-    echo -------------------------------------------------------------------
+-  fi
+-done;
+-
+-printf "\n\nYou should now login as the vsx0 user and run $TET_ROOT/setup.sh\n"
+-echo "Note that additional test suites can be installed by unpacking the"
+-echo "test suite tarball in $TET_ROOT/test_sets as the vsx0 user and re-running"
+-echo "$TET_ROOT/setup.sh (this will be ../setup.sh from the home directory)."
+-
+-
+
diff --git a/lsb_vsx/lsb_vsx-2.0-1-config/patches/03_host_other_fixes.patch b/lsb_vsx/lsb_vsx-2.0-1-config/patches/03_host_other_fixes.patch
--- a/lsb_vsx/lsb_vsx-2.0-1-config/patches/03_host_other_fixes.patch
+++ b/lsb_vsx/lsb_vsx-2.0-1-config/patches/03_host_other_fixes.patch
@@ -84,75 +84,6 @@ diff -Naur lsb_vsx-2.0-1/test_sets/scripts/vsx-pcts/post-build.sh lsb_vsx-2.0-1-
 +#	printf "Enter the root password:\n"
 +#	su root -c "sh scripts/vsx-pcts/nonexist_device.setup"
 +#fi
-diff -Naur lsb_vsx-2.0-1/test_sets/setup_testsets.sh lsb_vsx-2.0-1-host/test_sets/setup_testsets.sh
---- lsb_vsx-2.0-1/test_sets/setup_testsets.sh	2022-07-18 12:39:27.950040106 +0200
-+++ lsb_vsx-2.0-1-host/test_sets/setup_testsets.sh	2022-08-08 17:25:52.208621871 +0200
-@@ -135,16 +135,17 @@
- 
- #---------------------------------------------------------------------
- # Pre Configure testset scripts
--run_testset_config_script pre-config
-+#don' t create loopback disk for now
-+run_testset_config_script #pre-config
- 
- ######################################################################
- # Run config script
--printf "Run config.sh ..? [y] "
--read cmd
--if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
-+#printf "Run config.sh ..? [y] "
-+#read cmd
-+#if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
- 	config.sh
--fi
--printf "\n----------------------------------------------------------\n"
-+#fi
-+#printf "\n----------------------------------------------------------\n"
- 
- # Common cleanup needed
- # Fixup NSIG to _NSIG which common to all Linux's (and CLK_TCK)
-@@ -163,10 +164,10 @@
- ######################################################################
- # Build the test framework
- cd $INSTDIR
--
- printf "\n\n----------------------------------------------------------\n"
- printf "Building the test framework ... enter the root password\n"
--su root -c make
-+#we don't want to use root
-+make
- if [ $? -ne 0 ]; then
-   echo "Test framework compilation failed. Aborting"
-   exit 1
-@@ -186,8 +187,9 @@
- 
- ######################################################################
- # Parameterisation
--printf "Install tetexec.cfg ..? [y] "
--read cmd
-+#printf "Install tetexec.cfg ..? [y] "
-+#read cmd
-+cmd=y
- if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
- 
-   echo "Parameterizing the $TET_EXECUTE/tetexec.cfg file"
-@@ -217,11 +219,11 @@
- 
- ######################################################################
- # Build & Execute testsets
--printf "Build and Execute testsets ..? [y]"
--read cmd
--if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
--  sh run_testsets.sh
--fi
-+#printf "Build and Execute testsets ..? [y]"
-+#read cmd
-+#if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
-+#  sh run_testsets.sh
-+#fi
- 
- echo 
- echo "In order to re run the test suites at a later date run the"
 diff -Naur lsb_vsx-2.0-1/test_sets/SRC/common/vprog/vmake.sh lsb_vsx-2.0-1-host/test_sets/SRC/common/vprog/vmake.sh
 --- lsb_vsx-2.0-1/test_sets/SRC/common/vprog/vmake.sh	2022-07-18 12:39:27.954040018 +0200
 +++ lsb_vsx-2.0-1-host/test_sets/SRC/common/vprog/vmake.sh	2022-08-23 18:18:22.976834133 +0200
@@ -244,4 +175,394 @@ diff -Naur lsb_vsx-2.0-1/test_sets/SRC/install/targets/filldisc lsb_vsx-2.0-1-ho
 +	#cd $(MOUNT_DIR) && $(SCRIPTS)/filldisc.sh
 +	#sync; sleep 2; df $(MOUNT_DIR)
 +	#-umount $(MOUNT_DIR)
+ 
+--- lsb_vsx-2.0-1/test_sets/SRC/subsets/base/config_sub.sh	2022-07-18 12:39:27.962039842 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/subsets/base/config_sub.sh	2022-09-08 12:40:38.763291114 +0200
+@@ -4,36 +4,15 @@
+ # Ask for SIGNAL_SUPP if installing in a POSIX mode
+ # and not testing XNFS
+ 
++
++#Phoenix-RTOS support signal function
++
+ case "$TEST_MODE:$TEST_XNFS" in
+ *:[yY])
+ 	;;
+ POSIX*|FIPS*)
+-	if test -z "$SIGNAL_SUPP"
+-	then
+-		default=y
+-	else
+-		default=$SIGNAL_SUPP
+-	fi
+-	while :
+-	do
+-		getans "
+-Is the ANSI function signal() supported (y/n) [$default]? "
+-		if test -z "$ans"
+-		then
+-			ans=$default
+-		fi
+-		case "$ans" in
+-		y|n)
+-			SIGNAL_SUPP=$ans
+-			break
+-			;;
+-		*)
+-			;;
+-		esac
+-	done
+-	;;
+-*)
+ 	SIGNAL_SUPP=y
++	default=y
+ 	;;
+ esac
+ 
+--- lsb_vsx-2.0-1/test_sets/SRC/common/vport/nonposix.c	2022-07-18 12:39:27.954040018 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/common/vport/nonposix.c	2022-09-08 12:43:36.264008695 +0200
+@@ -282,75 +282,7 @@
+ 
+ #endif /* __STDC__ */
+ 
+-#ifndef __linux__
+-
+-public	int	opterr = 1;
+-public	int	optind = 1;
+-public	char	*optarg;
+-
+-public int
+-getopt(argc, argv, opts)
+-int	argc;
+-char	**argv, *opts;
+-{
+-	static int sp = 1;
+-	int c;
+-	char *cp;
+-
+-	if (sp == 1)
+-	{
+-		if (optind >= argc ||
+-		   argv[optind][0] != '-' || argv[optind][1] == '\0')
+-			return EOF;
+-		else if(strcmp(argv[optind], "--") == 0)
+-		{
+-			optind++;
+-			return EOF;
+-		}
+-	}
+-
+-	c = argv[optind][sp];
+-	if (c == ':' || (cp=strchr(opts, c)) == NULL)
+-	{
+-		if (opterr)
+-			(void) fprintf(stderr, "%s: illegal option -- %c\n",
+-				argv[0], c);
+-		if (argv[optind][++sp] == '\0')
+-		{
+-			optind++;
+-			sp = 1;
+-		}
+-		return '?';
+-	}
+-	if (*++cp == ':')
+-	{
+-		if (argv[optind][sp+1] != '\0')
+-			optarg = &argv[optind++][sp+1];
+-		else if(++optind >= argc)
+-		{
+-			if (opterr)
+-				(void) fprintf(stderr,
+-				    "%s: option requires an argument -- %c\n",
+-				    argv[0], c);
+-			sp = 1;
+-			return '?';
+-		} else
+-			optarg = argv[optind++];
+-		sp = 1;
+-	}
+-	else
+-	{
+-		if (argv[optind][++sp] == '\0')
+-		{
+-			sp = 1;
+-			optind++;
+-		}
+-		optarg = NULL;
+-	}
+-	return c;
+-}
+-
+-#endif /* __linux__ */
++/* Phoenix lib contains getopt func */
+ 
+ public int
+ isnan(x)
+@@ -359,123 +291,8 @@
+ 	return (x != x);
+ }
+ 
+-#ifndef __linux__
+-
+-#define	tst(a, b) (*mode == 'r' ? (b) : (a))
+-
+-static pid_t *popen_pid = NULL;
+-
+-public FILE *
+-popen(cmd, mode)
+-char	*cmd, *mode;
+-{
+-	int	p[2];
+-	int	myside, yourside;
+-	pid_t	*poptr, pid;
+-
+-	static long open_max;
+-
+-	if (popen_pid == NULL)
+-	{
+-		errno = 0;
+-		open_max = sysconf(_SC_OPEN_MAX);
+-		if (open_max < 0 && errno == 0)
+-			open_max = 256;
+-		if (open_max < 0 ||
+-		   (popen_pid = (pid_t *)calloc((size_t) open_max,
+-		   sizeof(pid_t))) == NULL)
+-			return NULL;
+-	}
+-
+-	if (pipe(p) < 0)
+-		return NULL;
+-
+-	myside = tst(p[1], p[0]);
+-	yourside = tst(p[0], p[1]);
+-
+-	if ((pid = fork()) == 0)
+-	{
+-		/* myside and yourside reverse roles in child */
+-		int	stdio;
+-
+-		/* close all pipes from other popen's */
+-		poptr = &popen_pid[open_max];
+-		while (poptr > popen_pid)
+-		{
+-			if (*--poptr != 0)
+-				(void) close(poptr - popen_pid);
+-		}
+-		stdio = tst(0, 1);
+-		(void) close(myside);
+-		(void) close(stdio);
+-		(void) fcntl(yourside, F_DUPFD, stdio);
+-		(void) close(yourside);
+-		(void) execlp("sh", "sh", "-c", cmd, (char *)0);
+-		_exit(1);
+-	}
+-	else if (pid == -1)
+-		return NULL;
+-
+-	popen_pid[myside] = pid;
+-	(void) close(yourside);
+-
+-	return fdopen(myside, mode);
+-}
+-
+-public int
+-pclose(ptr)
+-FILE	*ptr;
+-{
+-	int f, status, err = errno;
+-	pid_t p;
+-	sigset_t set, oset;
+-
+-	if (popen_pid == NULL)
+-	{
+-		/* no popen() calls made */
+-		errno = ECHILD;
+-		return SYSERROR;
+-	}
+-
+-	f = fileno(ptr);
+-	p = popen_pid[f];
+-	(void) fclose(ptr);
+-	popen_pid[f] = 0;
+-
+-	if (p <= 0)
+-	{
+-		/* no child to wait for */
+-		errno = ECHILD;
+-		return SYSERROR;
+-	}
+-
+-	(void) sigemptyset(&set);
+-	(void) sigaddset(&set, SIGHUP);
+-	(void) sigaddset(&set, SIGINT);
+-	(void) sigaddset(&set, SIGQUIT);
+-	(void) sigprocmask(SIG_BLOCK, &set, &oset);
+-
+-	if (waitpid(p, &status, 0) != p)
+-	{
+-		status = SYSERROR;
+-		err = errno;
+-	}
+-
+-	(void) sigprocmask(SIG_SETMASK, &oset, (sigset_t *)NULL);
+-	if (sigpending(&set) != SYSERROR &&
+-	   (sigismember(&set, SIGHUP) ||
+-	    sigismember(&set, SIGINT) ||
+-	    sigismember(&set, SIGQUIT)))
+-	{
+-		(void) sigsuspend(&oset);
+-		err = errno;
+-	}
+-
+-	errno = err;
+-	return status;
+-}
+ 
+-#endif /* __linux__ */
++/*Phoenix lib contains popen and pclose func */
+ 
+ #if !(__STDC__ > 0) && !ANSI_VPRINTF_FUNC 
+ 
+--- lsb_vsx-2.0-1/src/tet3/dtet2lib/notty.c	2022-07-18 12:39:27.906041074 +0200
++++ lsb_vsx-2.0-1-host/src/tet3/dtet2lib/notty.c	2022-09-08 13:56:32.235616417 +0200
+@@ -47,7 +47,8 @@
+ #    include <unistd.h>
+ #    include <errno.h>
+ #  else /* HAS_SETSID */
+-#    include <sys/ioctl.h>
++/*Change obsolete name, headers are the same */
++#    include <sys/stropts.h>
+ #    ifdef TIOCNOTTY
+ #      include <fcntl.h>
+ #    endif /* TIOCNOTTY */
+--- lsb_vsx-2.0-1/LSB.tools/userintf.c	2022-07-18 12:39:27.902041162 +0200
++++ lsb_vsx-2.0-1-host/LSB.tools/userintf.c	2022-09-08 14:09:19.353973329 +0200
+@@ -589,7 +589,7 @@
+ /* #define STREAMS_PTY	/* uncomment if pty's use STREAMS */
+ 
+ #ifdef STREAMS_PTY
+-#include <sys/stropts.h>
++#include <sys/ioctl.h>
+ #endif
+ 
+ public int
+--- lsb_vsx-2.0-1/test_sets/SRC/install/userintf/gen_termios	2022-07-18 12:39:27.962039842 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/install/userintf/gen_termios	2022-09-08 14:10:42.963443090 +0200
+@@ -69,7 +69,7 @@
+ /* #define STREAMS_PTY	/* uncomment if pty's use STREAMS */
+ 
+ #ifdef STREAMS_PTY
+-#include <sys/stropts.h>
++#include <sys/ioctl.h>
+ #endif
+ 
+ public int
+--- lsb_vsx-2.0-1/test_sets/SRC/common/vtools/hdrallow.c	2022-07-18 12:39:27.954040018 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/common/vtools/hdrallow.c	2022-09-08 14:11:33.396393202 +0200
+@@ -719,7 +719,7 @@
+ 			return 1;
+ #endif
+ 	}
+-	else if (strcmp(hdrname, "stropts.h") == 0)
++	else if (strcmp(hdrname, "ioctl.h") == 0)
+ 	{
+ 		/* Allow "bi_.*", "ic_.*", "l_.*", "sl_.*" and "str_.*" */
+ 
+--- lsb_vsx-2.0-1/test_sets/SRC/common/vport/userintfES.c	2022-07-18 12:39:27.954040018 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/common/vport/userintfES.c	2022-09-08 14:12:30.233514551 +0200
+@@ -727,7 +727,7 @@
+ #define STREAMS_PTY	/* uncomment if pty's use STREAMS */
+ 
+ #ifdef STREAMS_PTY
+-#include <sys/stropts.h>
++#include <sys/ioctl.h>
+ #endif
+ 
+ public int
+
+--- lsb_vsx-2.0-1/test_sets/SRC/install/scripts/install.sh	2022-07-22 10:57:39.567599982 +0200
++++ lsb_vsx-2.0-1-host/test_sets/SRC/install/scripts/install.sh	2022-09-08 15:41:05.054383634 +0200
+@@ -134,6 +134,10 @@
+     -e "/LONG_DOUBLE_SUPPORTED/s/ORTED.*$/ORTED	$DEF_LONG_DOUBLE/" \
+ 	../INC/std.h.orig > ../INC/std.h
+ 
++# This define resolves obsolete I_PUSH from ioctl.h
++
++echo "#define I_PUSH TIOCPKT" >> ../INC/std.h
++
+ #########################################################################
+ #									#
+ # Create the include files for use by VSX				#
+--- lsb_vsx-2.0-1/test_sets/setup_testsets.sh	2022-07-18 12:39:27.950040106 +0200
++++ lsb_vsx-2.0-1-host/test_sets/setup_testsets.sh	2022-09-08 18:15:32.848014622 +0200
+@@ -135,16 +135,17 @@
+ 
+ #---------------------------------------------------------------------
+ # Pre Configure testset scripts
+-run_testset_config_script pre-config
++#don' t create loopback disk for now
++run_testset_config_script #pre-config
+ 
+ ######################################################################
+ # Run config script
+-printf "Run config.sh ..? [y] "
+-read cmd
+-if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
++#printf "Run config.sh ..? [y] "
++#read cmd
++#if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
+ 	config.sh
+-fi
+-printf "\n----------------------------------------------------------\n"
++#fi
++#printf "\n----------------------------------------------------------\n"
+ 
+ # Common cleanup needed
+ # Fixup NSIG to _NSIG which common to all Linux's (and CLK_TCK)
+@@ -163,10 +164,10 @@
+ ######################################################################
+ # Build the test framework
+ cd $INSTDIR
+-
+ printf "\n\n----------------------------------------------------------\n"
+ printf "Building the test framework ... enter the root password\n"
+-su root -c make
++#we don't want to use root
++make
+ if [ $? -ne 0 ]; then
+   echo "Test framework compilation failed. Aborting"
+   exit 1
+@@ -186,8 +187,9 @@
+ 
+ ######################################################################
+ # Parameterisation
+-printf "Install tetexec.cfg ..? [y] "
+-read cmd
++#printf "Install tetexec.cfg ..? [y] "
++#read cmd
++cmd=y
+ if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
+ 
+   echo "Parameterizing the $TET_EXECUTE/tetexec.cfg file"
+@@ -215,13 +217,15 @@
+ 
+ fi
+ 
++# We only want to build test environment tools needed for building tests on host
++
+ ######################################################################
+ # Build & Execute testsets
+-printf "Build and Execute testsets ..? [y]"
+-read cmd
+-if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
+-  sh run_testsets.sh
+-fi
++#printf "Build and Execute testsets ..? [y]"
++#read cmd
++#if [ "$cmd" = "Y" -o "$cmd" = "y" -o "$cmd" = "" ] ; then
++#  sh run_testsets.sh
++#fi
+ 
+ echo 
+ echo "In order to re run the test suites at a later date run the"
  
