lsb_vsx: ensure build script halts on TET, VSX makefile errors
Allow all TET Makefile levels to execute, but capture any fail by recording it in a variable.
Ensure the script returns a non-zero exit code if any makefail fails. Previously, the script
could incorrectly return 0 due to relying on the return value of the last command.

A similar situation occurred in setup_testsets.sh, where a Makefile failure was only printed
but did not stop the subsequent execution.

JIRA: CI-538

diff --git a/lsb_vsx/patches/ps_VSX/04_install.patch b/lsb_vsx/patches/ps_VSX/04_install.patch
--- a/lsb_vsx/patches/ps_VSX/04_install.patch
+++ b/lsb_vsx/patches/ps_VSX/04_install.patch
@@ -1,5 +1,11 @@
---- lsb_vsx/test_sets/SRC/install/scripts/install.sh	2024-10-16 15:22:06.485884602 +0200
-+++ lsb_vsx.phoenix/test_sets/SRC/install/scripts/install.sh	2024-10-16 15:22:06.485884602 +0200
+--- lsb_vsx/test_sets/SRC/install/scripts/install.sh	2025-05-08 13:50:18.989594058 +0200
++++ lsb_vsx.phoenix/test_sets/SRC/install/scripts/install.sh	2025-05-09 15:43:56.245766734 +0200
+@@ -1,4 +1,4 @@
+-: use Bourne Shell
++#!/usr/bin/env bash
+ #########################################################################
+ #									#
+ #	SCCS:	@(#)install/scripts/install.sh	4.3 (03/03/98)  VSXgen release 1.4#
 @@ -141,6 +141,17 @@
  #########################################################################
  echo "
@@ -171,3 +177,26 @@
  # Set up the testroot 							#
  #									#
  #########################################################################
+@@ -681,14 +546,22 @@
+ 	then	echo "$dir make succeeded"
+ 	else	echo "$dir make failed:"
+ 		cat make.$target
++		exit 1
+ 	fi
+     )
++    test "$?" -eq 1 && fail=1
+ done
+ 
++if [ -n "$fail" ]; then
++	exit 1
++fi
++
+ # end of output tee'd to journal file
+ 
+ ) 2>&1 | tee "$JNLFILE"
+ 
++test "${PIPESTATUS[0]}" -eq "1" && exit 1
++
+ # clean up: remove temporary files
+ $rm_tmp1; $rm_tmp2
+ 
